### ISSUE TITLE
Microintegrator Dashboard not accessible after fresh installation

### ISSUE THREAD

**Issue by invent360** [wso2/docs-ei#2232] opened 2020-09-09 16:58 UTC
**Description:**
Microintegrator Dashboard not accessible after fresh installation

![Screenshot 2020-09-09 at 17 55 51](https://user-images.githubusercontent.com/46233704/92629269-fd472a00-f2c5-11ea-940d-692e868e4912.png)

**Comment by Vathsan** [comment] 2020-09-10 03:50
Hey @invent360, could you please let us know your OS details?

**Comment by invent360** [comment] 2020-09-10 07:06
@Vathsan thanks for picking this up.
I am using MacOS Catalina, 10.15.6
![Screenshot 2020-09-10 at 07 59 44](https://user-images.githubusercontent.com/46233704/92692370-f78c2b80-f33b-11ea-83bc-a26282c76f0b.png)
![Screenshot 2020-09-10 at 08 00 56](https://user-images.githubusercontent.com/46233704/92692378-f955ef00-f33b-11ea-85cd-2cd8cf3fbc74.png)

I also found out that the Dashboard binary is not found in the https://bintray.com/wso2/binaryGA/ hence the any attempt to build the image fails.

**Comment by Vathsan** [comment] 2020-09-10 11:09
@invent360, you may try starting the dashboard as a service [1] and see if that solves your initial issue.
Also, if you want to use the docker, you may find the images for MI, Monitoring Dashboard is available in [2], [3]

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/install_in_vm_installer/#running-the-mi-dashboard
[2] https://hub.docker.com/r/wso2/wso2mi
[3] https://hub.docker.com/r/wso2/wso2mi-dashboard

**Comment by nilminiwso2** [comment] 2020-09-17 06:19
@invent360: hope the issue is sorted now. To add to what Vathsan mentioned, you should be able to get the dashboard by started by following the instructions in the installation guide[1].

Closing this issue now. Let us know if you run into any issues.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/install_in_vm_installer/

**Closed by nilminiwso2** 2020-09-17 06:19 UTC
