### ISSUE TITLE
Improve experience in mobile view

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#992] opened 2019-11-04 07:04 UTC
The main three buttons on the first page[1]  aren't clickable from the mobile view. Please check this as well as other pages for improved mobile friendly usage.

[1] - https://ei.docs.wso2.com/

**Comment by nilminiwso2** [comment] 2020-09-07 07:38
This is no longer valid for the EI 7.1.0 release.
The problem is there in 7.0.0 though.
Shall we close this? @samgnaniah wdyt?

**Comment by samgnaniah** [comment] 2020-09-07 07:54
+1 to close.

**Closed** 2020-09-07 09:17 UTC
Labels: Priority/High, Type/UX
