### ISSUE TITLE
Doc Feedback: - Integration Studio 7.0.2 Embedded Micro-Integrator Error 

### ISSUE THREAD

**Issue by irunguh** [wso2/docs-ei#1747] opened 2020-07-09 13:28 UTC
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-datasource/

Hi,

There is a bug with Embedded Micro-Integrator tool in Integration Studio version 7.0.2.  I followed the tutorial and created my project as guided but can't run it due to a classNotFoundException  showw below:

ERROR {org.apache.axis2.transport.base.threads.NativeWorkerPool} - Uncaught exception java.lang.NoClassDefFoundError: org/wso2/carbon/dataservices/core/DBUtils
	at org.wso2.micro.integrator.management.apis.DataServiceResource.populateDataServiceList(DataServiceResource.java:94)
	at org.wso2.micro.integrator.management.apis.DataServiceResource.invoke(DataServiceResource.java:77)
	at org.wso2.micro.integrator.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:82)
	at org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:111)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.dataservices.core.DBUtils cannot be found by org.wso2.micro.integrator.management.apis_1.1.0.beta3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

I then exported my project to a standalone micro-integrator and everything worked without the Error. Kindly check. 

Thank you.

**Comment by nilminiwso2** [comment] 2020-09-17 07:17
Hi,

Could you try this by downloading the latest Integration Studio [1] or by getting the latest updates [2].

[1] https://wso2.com/integration/integration-studio/
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/installing-WSO2-Integration-Studio/#get-the-latest-updates

**Comment by nilminiwso2** [comment] 2020-12-11 06:05
Closing this issue as we were unable to reproduce it.
Kindly reopen if you find any further issues.
Thanks!

**Closed by nilminiwso2** 2020-12-11 06:05 UTC
Labels: bug, micro-integrator
