### ISSUE TITLE
Fix redirect

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#565] opened 2019-09-17 10:36 UTC
Configure redirects for the URL of EI 7.0.0 to the latest URL.

**Comment by dakshika** [comment] 2019-09-19 07:14
can you explain this properly with exact details

**Comment by samgnaniah** [comment] 2019-09-19 08:55
Let's say we have three releases.

EI 8.0.0 - Unreleased version
EI 7.2.0 - Latest GA release
EI 7.1.0 - Previous release
EI 7.0.0 - Previous release

EI 7.0.0 is accessible via a URL similar to ei.docs.wso2.com/en/ei700. This is the case for EI 7.1.0 as well. So it is conceivable that someone could try to access 7.2.0 docs as well using the versioned URL. What we require here is that is someone does enter the version number in the URL for EI 7.2.0, they will be redirected to the URL similar to ei.docs.wso2.com/en/latest.

**Comment by nilminiwso2** [comment] 2019-09-30 09:04
Original issue: https://github.com/wso2/docs-ei/issues/437

**Comment by nilminiwso2** [comment] 2020-09-10 08:22
closing this as the issue is now fixed.

**Closed by nilminiwso2** 2020-09-10 08:22 UTC
Labels: Priority/Highest, Type/UX
